service: serverless-module-3-aws
frameworkVersion: '3'
useDotenv: true
plugins:
  - serverless-offline
provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 512
  stage: dev
  timeout: 15
  region: eu-central-1
  environment:
    SECRET_KEY: ${env:SECRET_KEY}
    ACCESS_KEY_ID: ${env:ACCESS_KEY_ID}
    SECRET_ACCESS_KEY: ${env:SECRET_ACCESS_KEY}
    REGION: ${env:REGION}

functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
